// Code generated by protoc-gen-go. DO NOT EDIT.
// source: C2M.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2M2C_ChangeEquipItemPos_HeroToBagType int32

const (
	C2M2C_ChangeEquipItemPos_HeroToBag    C2M2C_ChangeEquipItemPos_HeroToBagType = 0
	C2M2C_ChangeEquipItemPos_BagToHero    C2M2C_ChangeEquipItemPos_HeroToBagType = 1
	C2M2C_ChangeEquipItemPos_BagToBag     C2M2C_ChangeEquipItemPos_HeroToBagType = 2
	C2M2C_ChangeEquipItemPos_SoldierToBag C2M2C_ChangeEquipItemPos_HeroToBagType = 3
	C2M2C_ChangeEquipItemPos_BagToSoldier C2M2C_ChangeEquipItemPos_HeroToBagType = 4
)

var C2M2C_ChangeEquipItemPos_HeroToBagType_name = map[int32]string{
	0: "HeroToBag",
	1: "BagToHero",
	2: "BagToBag",
	3: "SoldierToBag",
	4: "BagToSoldier",
}
var C2M2C_ChangeEquipItemPos_HeroToBagType_value = map[string]int32{
	"HeroToBag":    0,
	"BagToHero":    1,
	"BagToBag":     2,
	"SoldierToBag": 3,
	"BagToSoldier": 4,
}

func (x C2M2C_ChangeEquipItemPos_HeroToBagType) String() string {
	return proto.EnumName(C2M2C_ChangeEquipItemPos_HeroToBagType_name, int32(x))
}
func (C2M2C_ChangeEquipItemPos_HeroToBagType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{23, 0}
}

type C2M2C_BangDingZhang_ZhangHaoType int32

const (
	C2M2C_BangDingZhang_QQ     C2M2C_BangDingZhang_ZhangHaoType = 0
	C2M2C_BangDingZhang_WeiXin C2M2C_BangDingZhang_ZhangHaoType = 1
	C2M2C_BangDingZhang_Email  C2M2C_BangDingZhang_ZhangHaoType = 2
	C2M2C_BangDingZhang_Phone  C2M2C_BangDingZhang_ZhangHaoType = 3
)

var C2M2C_BangDingZhang_ZhangHaoType_name = map[int32]string{
	0: "QQ",
	1: "WeiXin",
	2: "Email",
	3: "Phone",
}
var C2M2C_BangDingZhang_ZhangHaoType_value = map[string]int32{
	"QQ":     0,
	"WeiXin": 1,
	"Email":  2,
	"Phone":  3,
}

func (x C2M2C_BangDingZhang_ZhangHaoType) String() string {
	return proto.EnumName(C2M2C_BangDingZhang_ZhangHaoType_name, int32(x))
}
func (C2M2C_BangDingZhang_ZhangHaoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{34, 0}
}

type Room struct {
	Owner                *RoomOwner    `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Members              []*RoomMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{0}
}
func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (dst *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(dst, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetOwner() *RoomOwner {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Room) GetMembers() []*RoomMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type LocalRole struct {
	RoleId               int64            `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	NickName             string           `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	AvatarId             int32            `protobuf:"varint,3,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Level                int32            `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Arrower              *FreeSoldierData `protobuf:"bytes,5,opt,name=arrower,proto3" json:"arrower,omitempty"`
	Daodun               *FreeSoldierData `protobuf:"bytes,6,opt,name=daodun,proto3" json:"daodun,omitempty"`
	Spear                *FreeSoldierData `protobuf:"bytes,7,opt,name=spear,proto3" json:"spear,omitempty"`
	Fashi                *FreeSoldierData `protobuf:"bytes,8,opt,name=fashi,proto3" json:"fashi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LocalRole) Reset()         { *m = LocalRole{} }
func (m *LocalRole) String() string { return proto.CompactTextString(m) }
func (*LocalRole) ProtoMessage()    {}
func (*LocalRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{1}
}
func (m *LocalRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalRole.Unmarshal(m, b)
}
func (m *LocalRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalRole.Marshal(b, m, deterministic)
}
func (dst *LocalRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalRole.Merge(dst, src)
}
func (m *LocalRole) XXX_Size() int {
	return xxx_messageInfo_LocalRole.Size(m)
}
func (m *LocalRole) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalRole.DiscardUnknown(m)
}

var xxx_messageInfo_LocalRole proto.InternalMessageInfo

func (m *LocalRole) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *LocalRole) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *LocalRole) GetAvatarId() int32 {
	if m != nil {
		return m.AvatarId
	}
	return 0
}

func (m *LocalRole) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *LocalRole) GetArrower() *FreeSoldierData {
	if m != nil {
		return m.Arrower
	}
	return nil
}

func (m *LocalRole) GetDaodun() *FreeSoldierData {
	if m != nil {
		return m.Daodun
	}
	return nil
}

func (m *LocalRole) GetSpear() *FreeSoldierData {
	if m != nil {
		return m.Spear
	}
	return nil
}

func (m *LocalRole) GetFashi() *FreeSoldierData {
	if m != nil {
		return m.Fashi
	}
	return nil
}

type FreeSoldierData struct {
	PlayerType           int32    `protobuf:"varint,1,opt,name=playerType,proto3" json:"playerType,omitempty"`
	CarrierType          int32    `protobuf:"varint,2,opt,name=carrierType,proto3" json:"carrierType,omitempty"`
	TouKuiId             int32    `protobuf:"varint,3,opt,name=touKuiId,proto3" json:"touKuiId,omitempty"`
	BodyId               int32    `protobuf:"varint,4,opt,name=bodyId,proto3" json:"bodyId,omitempty"`
	WeapId               int32    `protobuf:"varint,5,opt,name=weapId,proto3" json:"weapId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreeSoldierData) Reset()         { *m = FreeSoldierData{} }
func (m *FreeSoldierData) String() string { return proto.CompactTextString(m) }
func (*FreeSoldierData) ProtoMessage()    {}
func (*FreeSoldierData) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{2}
}
func (m *FreeSoldierData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreeSoldierData.Unmarshal(m, b)
}
func (m *FreeSoldierData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreeSoldierData.Marshal(b, m, deterministic)
}
func (dst *FreeSoldierData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreeSoldierData.Merge(dst, src)
}
func (m *FreeSoldierData) XXX_Size() int {
	return xxx_messageInfo_FreeSoldierData.Size(m)
}
func (m *FreeSoldierData) XXX_DiscardUnknown() {
	xxx_messageInfo_FreeSoldierData.DiscardUnknown(m)
}

var xxx_messageInfo_FreeSoldierData proto.InternalMessageInfo

func (m *FreeSoldierData) GetPlayerType() int32 {
	if m != nil {
		return m.PlayerType
	}
	return 0
}

func (m *FreeSoldierData) GetCarrierType() int32 {
	if m != nil {
		return m.CarrierType
	}
	return 0
}

func (m *FreeSoldierData) GetTouKuiId() int32 {
	if m != nil {
		return m.TouKuiId
	}
	return 0
}

func (m *FreeSoldierData) GetBodyId() int32 {
	if m != nil {
		return m.BodyId
	}
	return 0
}

func (m *FreeSoldierData) GetWeapId() int32 {
	if m != nil {
		return m.WeapId
	}
	return 0
}

type RoomMember struct {
	JoinerId             int64            `protobuf:"varint,1,opt,name=joinerId,proto3" json:"joinerId,omitempty"`
	JoinerName           string           `protobuf:"bytes,2,opt,name=joinerName,proto3" json:"joinerName,omitempty"`
	JoinerIconId         int32            `protobuf:"varint,3,opt,name=joinerIconId,proto3" json:"joinerIconId,omitempty"`
	GroupId              int32            `protobuf:"varint,4,opt,name=groupId,proto3" json:"groupId,omitempty"`
	JoinerLevel          int32            `protobuf:"varint,5,opt,name=joinerLevel,proto3" json:"joinerLevel,omitempty"`
	Ready                bool             `protobuf:"varint,6,opt,name=ready,proto3" json:"ready,omitempty"`
	Arrower              *FreeSoldierData `protobuf:"bytes,7,opt,name=arrower,proto3" json:"arrower,omitempty"`
	Daodun               *FreeSoldierData `protobuf:"bytes,8,opt,name=daodun,proto3" json:"daodun,omitempty"`
	Spear                *FreeSoldierData `protobuf:"bytes,9,opt,name=spear,proto3" json:"spear,omitempty"`
	Fashi                *FreeSoldierData `protobuf:"bytes,10,opt,name=fashi,proto3" json:"fashi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RoomMember) Reset()         { *m = RoomMember{} }
func (m *RoomMember) String() string { return proto.CompactTextString(m) }
func (*RoomMember) ProtoMessage()    {}
func (*RoomMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{3}
}
func (m *RoomMember) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMember.Unmarshal(m, b)
}
func (m *RoomMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMember.Marshal(b, m, deterministic)
}
func (dst *RoomMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMember.Merge(dst, src)
}
func (m *RoomMember) XXX_Size() int {
	return xxx_messageInfo_RoomMember.Size(m)
}
func (m *RoomMember) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMember.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMember proto.InternalMessageInfo

func (m *RoomMember) GetJoinerId() int64 {
	if m != nil {
		return m.JoinerId
	}
	return 0
}

func (m *RoomMember) GetJoinerName() string {
	if m != nil {
		return m.JoinerName
	}
	return ""
}

func (m *RoomMember) GetJoinerIconId() int32 {
	if m != nil {
		return m.JoinerIconId
	}
	return 0
}

func (m *RoomMember) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *RoomMember) GetJoinerLevel() int32 {
	if m != nil {
		return m.JoinerLevel
	}
	return 0
}

func (m *RoomMember) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func (m *RoomMember) GetArrower() *FreeSoldierData {
	if m != nil {
		return m.Arrower
	}
	return nil
}

func (m *RoomMember) GetDaodun() *FreeSoldierData {
	if m != nil {
		return m.Daodun
	}
	return nil
}

func (m *RoomMember) GetSpear() *FreeSoldierData {
	if m != nil {
		return m.Spear
	}
	return nil
}

func (m *RoomMember) GetFashi() *FreeSoldierData {
	if m != nil {
		return m.Fashi
	}
	return nil
}

type RoomOwner struct {
	GameType             int32            `protobuf:"varint,1,opt,name=gameType,proto3" json:"gameType,omitempty"`
	RoomName             string           `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	MaxPlayerNum         int32            `protobuf:"varint,3,opt,name=maxPlayerNum,proto3" json:"maxPlayerNum,omitempty"`
	MapId                int32            `protobuf:"varint,4,opt,name=mapId,proto3" json:"mapId,omitempty"`
	RoomOwnerName        string           `protobuf:"bytes,5,opt,name=roomOwnerName,proto3" json:"roomOwnerName,omitempty"`
	RoomOwnerId          int64            `protobuf:"varint,6,opt,name=roomOwnerId,proto3" json:"roomOwnerId,omitempty"`
	RoomId               int32            `protobuf:"varint,7,opt,name=roomId,proto3" json:"roomId,omitempty"`
	CurPlayeNum          int32            `protobuf:"varint,8,opt,name=curPlayeNum,proto3" json:"curPlayeNum,omitempty"`
	RoomOwnerGroupId     int32            `protobuf:"varint,9,opt,name=roomOwnerGroupId,proto3" json:"roomOwnerGroupId,omitempty"`
	IsWarFow             bool             `protobuf:"varint,10,opt,name=isWarFow,proto3" json:"isWarFow,omitempty"`
	RoomOwnerAvatarId    int32            `protobuf:"varint,11,opt,name=roomOwnerAvatarId,proto3" json:"roomOwnerAvatarId,omitempty"`
	Arrower              *FreeSoldierData `protobuf:"bytes,12,opt,name=arrower,proto3" json:"arrower,omitempty"`
	Daodun               *FreeSoldierData `protobuf:"bytes,13,opt,name=daodun,proto3" json:"daodun,omitempty"`
	Spear                *FreeSoldierData `protobuf:"bytes,14,opt,name=spear,proto3" json:"spear,omitempty"`
	Fashi                *FreeSoldierData `protobuf:"bytes,15,opt,name=fashi,proto3" json:"fashi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RoomOwner) Reset()         { *m = RoomOwner{} }
func (m *RoomOwner) String() string { return proto.CompactTextString(m) }
func (*RoomOwner) ProtoMessage()    {}
func (*RoomOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{4}
}
func (m *RoomOwner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomOwner.Unmarshal(m, b)
}
func (m *RoomOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomOwner.Marshal(b, m, deterministic)
}
func (dst *RoomOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomOwner.Merge(dst, src)
}
func (m *RoomOwner) XXX_Size() int {
	return xxx_messageInfo_RoomOwner.Size(m)
}
func (m *RoomOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomOwner.DiscardUnknown(m)
}

var xxx_messageInfo_RoomOwner proto.InternalMessageInfo

func (m *RoomOwner) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *RoomOwner) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *RoomOwner) GetMaxPlayerNum() int32 {
	if m != nil {
		return m.MaxPlayerNum
	}
	return 0
}

func (m *RoomOwner) GetMapId() int32 {
	if m != nil {
		return m.MapId
	}
	return 0
}

func (m *RoomOwner) GetRoomOwnerName() string {
	if m != nil {
		return m.RoomOwnerName
	}
	return ""
}

func (m *RoomOwner) GetRoomOwnerId() int64 {
	if m != nil {
		return m.RoomOwnerId
	}
	return 0
}

func (m *RoomOwner) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomOwner) GetCurPlayeNum() int32 {
	if m != nil {
		return m.CurPlayeNum
	}
	return 0
}

func (m *RoomOwner) GetRoomOwnerGroupId() int32 {
	if m != nil {
		return m.RoomOwnerGroupId
	}
	return 0
}

func (m *RoomOwner) GetIsWarFow() bool {
	if m != nil {
		return m.IsWarFow
	}
	return false
}

func (m *RoomOwner) GetRoomOwnerAvatarId() int32 {
	if m != nil {
		return m.RoomOwnerAvatarId
	}
	return 0
}

func (m *RoomOwner) GetArrower() *FreeSoldierData {
	if m != nil {
		return m.Arrower
	}
	return nil
}

func (m *RoomOwner) GetDaodun() *FreeSoldierData {
	if m != nil {
		return m.Daodun
	}
	return nil
}

func (m *RoomOwner) GetSpear() *FreeSoldierData {
	if m != nil {
		return m.Spear
	}
	return nil
}

func (m *RoomOwner) GetFashi() *FreeSoldierData {
	if m != nil {
		return m.Fashi
	}
	return nil
}

// 操作指令
type Command struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	CommandType          int32    `protobuf:"varint,2,opt,name=commandType,proto3" json:"commandType,omitempty"`
	Param                string   `protobuf:"bytes,3,opt,name=param,proto3" json:"param,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{5}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Command) GetCommandType() int32 {
	if m != nil {
		return m.CommandType
	}
	return 0
}

func (m *Command) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

// 创建房间
type C2M_CreateRoom struct {
	Room                 *RoomOwner `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *C2M_CreateRoom) Reset()         { *m = C2M_CreateRoom{} }
func (m *C2M_CreateRoom) String() string { return proto.CompactTextString(m) }
func (*C2M_CreateRoom) ProtoMessage()    {}
func (*C2M_CreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{6}
}
func (m *C2M_CreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_CreateRoom.Unmarshal(m, b)
}
func (m *C2M_CreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_CreateRoom.Marshal(b, m, deterministic)
}
func (dst *C2M_CreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_CreateRoom.Merge(dst, src)
}
func (m *C2M_CreateRoom) XXX_Size() int {
	return xxx_messageInfo_C2M_CreateRoom.Size(m)
}
func (m *C2M_CreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_CreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_CreateRoom proto.InternalMessageInfo

func (m *C2M_CreateRoom) GetRoom() *RoomOwner {
	if m != nil {
		return m.Room
	}
	return nil
}

// 请求刷新房间列表
type C2M_ReqRefreshRoomList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ReqRefreshRoomList) Reset()         { *m = C2M_ReqRefreshRoomList{} }
func (m *C2M_ReqRefreshRoomList) String() string { return proto.CompactTextString(m) }
func (*C2M_ReqRefreshRoomList) ProtoMessage()    {}
func (*C2M_ReqRefreshRoomList) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{7}
}
func (m *C2M_ReqRefreshRoomList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ReqRefreshRoomList.Unmarshal(m, b)
}
func (m *C2M_ReqRefreshRoomList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ReqRefreshRoomList.Marshal(b, m, deterministic)
}
func (dst *C2M_ReqRefreshRoomList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ReqRefreshRoomList.Merge(dst, src)
}
func (m *C2M_ReqRefreshRoomList) XXX_Size() int {
	return xxx_messageInfo_C2M_ReqRefreshRoomList.Size(m)
}
func (m *C2M_ReqRefreshRoomList) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ReqRefreshRoomList.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ReqRefreshRoomList proto.InternalMessageInfo

// 请求加入房间
type C2M_ReqJoinRoom struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ReqJoinRoom) Reset()         { *m = C2M_ReqJoinRoom{} }
func (m *C2M_ReqJoinRoom) String() string { return proto.CompactTextString(m) }
func (*C2M_ReqJoinRoom) ProtoMessage()    {}
func (*C2M_ReqJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{8}
}
func (m *C2M_ReqJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ReqJoinRoom.Unmarshal(m, b)
}
func (m *C2M_ReqJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ReqJoinRoom.Marshal(b, m, deterministic)
}
func (dst *C2M_ReqJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ReqJoinRoom.Merge(dst, src)
}
func (m *C2M_ReqJoinRoom) XXX_Size() int {
	return xxx_messageInfo_C2M_ReqJoinRoom.Size(m)
}
func (m *C2M_ReqJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ReqJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ReqJoinRoom proto.InternalMessageInfo

func (m *C2M_ReqJoinRoom) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// 本地请求加入房间
type C2M_ReqLocalJoinRoom struct {
	RoomId               int32      `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Role                 *LocalRole `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *C2M_ReqLocalJoinRoom) Reset()         { *m = C2M_ReqLocalJoinRoom{} }
func (m *C2M_ReqLocalJoinRoom) String() string { return proto.CompactTextString(m) }
func (*C2M_ReqLocalJoinRoom) ProtoMessage()    {}
func (*C2M_ReqLocalJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{9}
}
func (m *C2M_ReqLocalJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ReqLocalJoinRoom.Unmarshal(m, b)
}
func (m *C2M_ReqLocalJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ReqLocalJoinRoom.Marshal(b, m, deterministic)
}
func (dst *C2M_ReqLocalJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ReqLocalJoinRoom.Merge(dst, src)
}
func (m *C2M_ReqLocalJoinRoom) XXX_Size() int {
	return xxx_messageInfo_C2M_ReqLocalJoinRoom.Size(m)
}
func (m *C2M_ReqLocalJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ReqLocalJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ReqLocalJoinRoom proto.InternalMessageInfo

func (m *C2M_ReqLocalJoinRoom) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *C2M_ReqLocalJoinRoom) GetRole() *LocalRole {
	if m != nil {
		return m.Role
	}
	return nil
}

// 请求开始战斗
type C2M_StartBattle struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_StartBattle) Reset()         { *m = C2M_StartBattle{} }
func (m *C2M_StartBattle) String() string { return proto.CompactTextString(m) }
func (*C2M_StartBattle) ProtoMessage()    {}
func (*C2M_StartBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{10}
}
func (m *C2M_StartBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_StartBattle.Unmarshal(m, b)
}
func (m *C2M_StartBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_StartBattle.Marshal(b, m, deterministic)
}
func (dst *C2M_StartBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_StartBattle.Merge(dst, src)
}
func (m *C2M_StartBattle) XXX_Size() int {
	return xxx_messageInfo_C2M_StartBattle.Size(m)
}
func (m *C2M_StartBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_StartBattle.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_StartBattle proto.InternalMessageInfo

// 请求准备
type C2M_ReqReady struct {
	Ready                bool     `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ReqReady) Reset()         { *m = C2M_ReqReady{} }
func (m *C2M_ReqReady) String() string { return proto.CompactTextString(m) }
func (*C2M_ReqReady) ProtoMessage()    {}
func (*C2M_ReqReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{11}
}
func (m *C2M_ReqReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ReqReady.Unmarshal(m, b)
}
func (m *C2M_ReqReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ReqReady.Marshal(b, m, deterministic)
}
func (dst *C2M_ReqReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ReqReady.Merge(dst, src)
}
func (m *C2M_ReqReady) XXX_Size() int {
	return xxx_messageInfo_C2M_ReqReady.Size(m)
}
func (m *C2M_ReqReady) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ReqReady.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ReqReady proto.InternalMessageInfo

func (m *C2M_ReqReady) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

// 本地请求准备
type C2M_ReqLocalReady struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Ready                bool     `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ReqLocalReady) Reset()         { *m = C2M_ReqLocalReady{} }
func (m *C2M_ReqLocalReady) String() string { return proto.CompactTextString(m) }
func (*C2M_ReqLocalReady) ProtoMessage()    {}
func (*C2M_ReqLocalReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{12}
}
func (m *C2M_ReqLocalReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ReqLocalReady.Unmarshal(m, b)
}
func (m *C2M_ReqLocalReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ReqLocalReady.Marshal(b, m, deterministic)
}
func (dst *C2M_ReqLocalReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ReqLocalReady.Merge(dst, src)
}
func (m *C2M_ReqLocalReady) XXX_Size() int {
	return xxx_messageInfo_C2M_ReqLocalReady.Size(m)
}
func (m *C2M_ReqLocalReady) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ReqLocalReady.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ReqLocalReady proto.InternalMessageInfo

func (m *C2M_ReqLocalReady) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *C2M_ReqLocalReady) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

// 加载完成
type C2M_LoadFinished struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_LoadFinished) Reset()         { *m = C2M_LoadFinished{} }
func (m *C2M_LoadFinished) String() string { return proto.CompactTextString(m) }
func (*C2M_LoadFinished) ProtoMessage()    {}
func (*C2M_LoadFinished) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{13}
}
func (m *C2M_LoadFinished) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_LoadFinished.Unmarshal(m, b)
}
func (m *C2M_LoadFinished) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_LoadFinished.Marshal(b, m, deterministic)
}
func (dst *C2M_LoadFinished) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_LoadFinished.Merge(dst, src)
}
func (m *C2M_LoadFinished) XXX_Size() int {
	return xxx_messageInfo_C2M_LoadFinished.Size(m)
}
func (m *C2M_LoadFinished) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_LoadFinished.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_LoadFinished proto.InternalMessageInfo

// 本地加载完成
type C2M_LocalLoadFinished struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_LocalLoadFinished) Reset()         { *m = C2M_LocalLoadFinished{} }
func (m *C2M_LocalLoadFinished) String() string { return proto.CompactTextString(m) }
func (*C2M_LocalLoadFinished) ProtoMessage()    {}
func (*C2M_LocalLoadFinished) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{14}
}
func (m *C2M_LocalLoadFinished) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_LocalLoadFinished.Unmarshal(m, b)
}
func (m *C2M_LocalLoadFinished) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_LocalLoadFinished.Marshal(b, m, deterministic)
}
func (dst *C2M_LocalLoadFinished) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_LocalLoadFinished.Merge(dst, src)
}
func (m *C2M_LocalLoadFinished) XXX_Size() int {
	return xxx_messageInfo_C2M_LocalLoadFinished.Size(m)
}
func (m *C2M_LocalLoadFinished) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_LocalLoadFinished.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_LocalLoadFinished proto.InternalMessageInfo

func (m *C2M_LocalLoadFinished) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

// 玩家的操作指令
type C2M_Command struct {
	Cmd                  *Command `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_Command) Reset()         { *m = C2M_Command{} }
func (m *C2M_Command) String() string { return proto.CompactTextString(m) }
func (*C2M_Command) ProtoMessage()    {}
func (*C2M_Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{15}
}
func (m *C2M_Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_Command.Unmarshal(m, b)
}
func (m *C2M_Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_Command.Marshal(b, m, deterministic)
}
func (dst *C2M_Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_Command.Merge(dst, src)
}
func (m *C2M_Command) XXX_Size() int {
	return xxx_messageInfo_C2M_Command.Size(m)
}
func (m *C2M_Command) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_Command.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_Command proto.InternalMessageInfo

func (m *C2M_Command) GetCmd() *Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

// 赢得一场战役
type C2M_WinBattle struct {
	Seed                 int32    `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	BattleId             int32    `protobuf:"varint,2,opt,name=battleId,proto3" json:"battleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_WinBattle) Reset()         { *m = C2M_WinBattle{} }
func (m *C2M_WinBattle) String() string { return proto.CompactTextString(m) }
func (*C2M_WinBattle) ProtoMessage()    {}
func (*C2M_WinBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{16}
}
func (m *C2M_WinBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_WinBattle.Unmarshal(m, b)
}
func (m *C2M_WinBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_WinBattle.Marshal(b, m, deterministic)
}
func (dst *C2M_WinBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_WinBattle.Merge(dst, src)
}
func (m *C2M_WinBattle) XXX_Size() int {
	return xxx_messageInfo_C2M_WinBattle.Size(m)
}
func (m *C2M_WinBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_WinBattle.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_WinBattle proto.InternalMessageInfo

func (m *C2M_WinBattle) GetSeed() int32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *C2M_WinBattle) GetBattleId() int32 {
	if m != nil {
		return m.BattleId
	}
	return 0
}

// 输一次战役
type C2M_FailedBattle struct {
	Seed                 int32    `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_FailedBattle) Reset()         { *m = C2M_FailedBattle{} }
func (m *C2M_FailedBattle) String() string { return proto.CompactTextString(m) }
func (*C2M_FailedBattle) ProtoMessage()    {}
func (*C2M_FailedBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{17}
}
func (m *C2M_FailedBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_FailedBattle.Unmarshal(m, b)
}
func (m *C2M_FailedBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_FailedBattle.Marshal(b, m, deterministic)
}
func (dst *C2M_FailedBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_FailedBattle.Merge(dst, src)
}
func (m *C2M_FailedBattle) XXX_Size() int {
	return xxx_messageInfo_C2M_FailedBattle.Size(m)
}
func (m *C2M_FailedBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_FailedBattle.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_FailedBattle proto.InternalMessageInfo

func (m *C2M_FailedBattle) GetSeed() int32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

// 观看广告
type C2M_WatchAds struct {
	IsBanner             bool     `protobuf:"varint,1,opt,name=isBanner,proto3" json:"isBanner,omitempty"`
	Seed                 int32    `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_WatchAds) Reset()         { *m = C2M_WatchAds{} }
func (m *C2M_WatchAds) String() string { return proto.CompactTextString(m) }
func (*C2M_WatchAds) ProtoMessage()    {}
func (*C2M_WatchAds) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{18}
}
func (m *C2M_WatchAds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_WatchAds.Unmarshal(m, b)
}
func (m *C2M_WatchAds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_WatchAds.Marshal(b, m, deterministic)
}
func (dst *C2M_WatchAds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_WatchAds.Merge(dst, src)
}
func (m *C2M_WatchAds) XXX_Size() int {
	return xxx_messageInfo_C2M_WatchAds.Size(m)
}
func (m *C2M_WatchAds) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_WatchAds.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_WatchAds proto.InternalMessageInfo

func (m *C2M_WatchAds) GetIsBanner() bool {
	if m != nil {
		return m.IsBanner
	}
	return false
}

func (m *C2M_WatchAds) GetSeed() int32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

// 玩家修改昵称
type C2M_ChangeNickName struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ChangeNickName) Reset()         { *m = C2M_ChangeNickName{} }
func (m *C2M_ChangeNickName) String() string { return proto.CompactTextString(m) }
func (*C2M_ChangeNickName) ProtoMessage()    {}
func (*C2M_ChangeNickName) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{19}
}
func (m *C2M_ChangeNickName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ChangeNickName.Unmarshal(m, b)
}
func (m *C2M_ChangeNickName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ChangeNickName.Marshal(b, m, deterministic)
}
func (dst *C2M_ChangeNickName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ChangeNickName.Merge(dst, src)
}
func (m *C2M_ChangeNickName) XXX_Size() int {
	return xxx_messageInfo_C2M_ChangeNickName.Size(m)
}
func (m *C2M_ChangeNickName) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ChangeNickName.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ChangeNickName proto.InternalMessageInfo

func (m *C2M_ChangeNickName) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

// 玩家修改头像id
type C2M_ChangeAvatarIcon struct {
	AvatarId             int32    `protobuf:"varint,1,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ChangeAvatarIcon) Reset()         { *m = C2M_ChangeAvatarIcon{} }
func (m *C2M_ChangeAvatarIcon) String() string { return proto.CompactTextString(m) }
func (*C2M_ChangeAvatarIcon) ProtoMessage()    {}
func (*C2M_ChangeAvatarIcon) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{20}
}
func (m *C2M_ChangeAvatarIcon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ChangeAvatarIcon.Unmarshal(m, b)
}
func (m *C2M_ChangeAvatarIcon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ChangeAvatarIcon.Marshal(b, m, deterministic)
}
func (dst *C2M_ChangeAvatarIcon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ChangeAvatarIcon.Merge(dst, src)
}
func (m *C2M_ChangeAvatarIcon) XXX_Size() int {
	return xxx_messageInfo_C2M_ChangeAvatarIcon.Size(m)
}
func (m *C2M_ChangeAvatarIcon) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ChangeAvatarIcon.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ChangeAvatarIcon proto.InternalMessageInfo

func (m *C2M_ChangeAvatarIcon) GetAvatarId() int32 {
	if m != nil {
		return m.AvatarId
	}
	return 0
}

// 玩家修改性别
type C2M_ChangeSex struct {
	Sex                  int32    `protobuf:"varint,1,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ChangeSex) Reset()         { *m = C2M_ChangeSex{} }
func (m *C2M_ChangeSex) String() string { return proto.CompactTextString(m) }
func (*C2M_ChangeSex) ProtoMessage()    {}
func (*C2M_ChangeSex) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{21}
}
func (m *C2M_ChangeSex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ChangeSex.Unmarshal(m, b)
}
func (m *C2M_ChangeSex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ChangeSex.Marshal(b, m, deterministic)
}
func (dst *C2M_ChangeSex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ChangeSex.Merge(dst, src)
}
func (m *C2M_ChangeSex) XXX_Size() int {
	return xxx_messageInfo_C2M_ChangeSex.Size(m)
}
func (m *C2M_ChangeSex) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ChangeSex.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ChangeSex proto.InternalMessageInfo

func (m *C2M_ChangeSex) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

// 玩家签名修改
type C2M_ChangeSign struct {
	Sign                 string   `protobuf:"bytes,1,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_ChangeSign) Reset()         { *m = C2M_ChangeSign{} }
func (m *C2M_ChangeSign) String() string { return proto.CompactTextString(m) }
func (*C2M_ChangeSign) ProtoMessage()    {}
func (*C2M_ChangeSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{22}
}
func (m *C2M_ChangeSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_ChangeSign.Unmarshal(m, b)
}
func (m *C2M_ChangeSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_ChangeSign.Marshal(b, m, deterministic)
}
func (dst *C2M_ChangeSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_ChangeSign.Merge(dst, src)
}
func (m *C2M_ChangeSign) XXX_Size() int {
	return xxx_messageInfo_C2M_ChangeSign.Size(m)
}
func (m *C2M_ChangeSign) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_ChangeSign.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_ChangeSign proto.InternalMessageInfo

func (m *C2M_ChangeSign) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

// 玩家改变装备位置
type C2M2C_ChangeEquipItemPos struct {
	ChangeType           C2M2C_ChangeEquipItemPos_HeroToBagType `protobuf:"varint,1,opt,name=changeType,proto3,enum=message.C2M2C_ChangeEquipItemPos_HeroToBagType" json:"changeType,omitempty"`
	Index1               int32                                  `protobuf:"varint,2,opt,name=index1,proto3" json:"index1,omitempty"`
	Index2               int32                                  `protobuf:"varint,3,opt,name=index2,proto3" json:"index2,omitempty"`
	HeroId               int32                                  `protobuf:"varint,4,opt,name=heroId,proto3" json:"heroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *C2M2C_ChangeEquipItemPos) Reset()         { *m = C2M2C_ChangeEquipItemPos{} }
func (m *C2M2C_ChangeEquipItemPos) String() string { return proto.CompactTextString(m) }
func (*C2M2C_ChangeEquipItemPos) ProtoMessage()    {}
func (*C2M2C_ChangeEquipItemPos) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{23}
}
func (m *C2M2C_ChangeEquipItemPos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M2C_ChangeEquipItemPos.Unmarshal(m, b)
}
func (m *C2M2C_ChangeEquipItemPos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M2C_ChangeEquipItemPos.Marshal(b, m, deterministic)
}
func (dst *C2M2C_ChangeEquipItemPos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M2C_ChangeEquipItemPos.Merge(dst, src)
}
func (m *C2M2C_ChangeEquipItemPos) XXX_Size() int {
	return xxx_messageInfo_C2M2C_ChangeEquipItemPos.Size(m)
}
func (m *C2M2C_ChangeEquipItemPos) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M2C_ChangeEquipItemPos.DiscardUnknown(m)
}

var xxx_messageInfo_C2M2C_ChangeEquipItemPos proto.InternalMessageInfo

func (m *C2M2C_ChangeEquipItemPos) GetChangeType() C2M2C_ChangeEquipItemPos_HeroToBagType {
	if m != nil {
		return m.ChangeType
	}
	return C2M2C_ChangeEquipItemPos_HeroToBag
}

func (m *C2M2C_ChangeEquipItemPos) GetIndex1() int32 {
	if m != nil {
		return m.Index1
	}
	return 0
}

func (m *C2M2C_ChangeEquipItemPos) GetIndex2() int32 {
	if m != nil {
		return m.Index2
	}
	return 0
}

func (m *C2M2C_ChangeEquipItemPos) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

// 玩家退出房间
type C2M_QuitRoom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_QuitRoom) Reset()         { *m = C2M_QuitRoom{} }
func (m *C2M_QuitRoom) String() string { return proto.CompactTextString(m) }
func (*C2M_QuitRoom) ProtoMessage()    {}
func (*C2M_QuitRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{24}
}
func (m *C2M_QuitRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_QuitRoom.Unmarshal(m, b)
}
func (m *C2M_QuitRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_QuitRoom.Marshal(b, m, deterministic)
}
func (dst *C2M_QuitRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_QuitRoom.Merge(dst, src)
}
func (m *C2M_QuitRoom) XXX_Size() int {
	return xxx_messageInfo_C2M_QuitRoom.Size(m)
}
func (m *C2M_QuitRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_QuitRoom.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_QuitRoom proto.InternalMessageInfo

// 玩家本地退出
type C2M_LocalQuitRoom struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_LocalQuitRoom) Reset()         { *m = C2M_LocalQuitRoom{} }
func (m *C2M_LocalQuitRoom) String() string { return proto.CompactTextString(m) }
func (*C2M_LocalQuitRoom) ProtoMessage()    {}
func (*C2M_LocalQuitRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{25}
}
func (m *C2M_LocalQuitRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_LocalQuitRoom.Unmarshal(m, b)
}
func (m *C2M_LocalQuitRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_LocalQuitRoom.Marshal(b, m, deterministic)
}
func (dst *C2M_LocalQuitRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_LocalQuitRoom.Merge(dst, src)
}
func (m *C2M_LocalQuitRoom) XXX_Size() int {
	return xxx_messageInfo_C2M_LocalQuitRoom.Size(m)
}
func (m *C2M_LocalQuitRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_LocalQuitRoom.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_LocalQuitRoom proto.InternalMessageInfo

func (m *C2M_LocalQuitRoom) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

// 玩家买英雄
type C2M_BuyHero struct {
	HeroId               int32    `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_BuyHero) Reset()         { *m = C2M_BuyHero{} }
func (m *C2M_BuyHero) String() string { return proto.CompactTextString(m) }
func (*C2M_BuyHero) ProtoMessage()    {}
func (*C2M_BuyHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{26}
}
func (m *C2M_BuyHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_BuyHero.Unmarshal(m, b)
}
func (m *C2M_BuyHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_BuyHero.Marshal(b, m, deterministic)
}
func (dst *C2M_BuyHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_BuyHero.Merge(dst, src)
}
func (m *C2M_BuyHero) XXX_Size() int {
	return xxx_messageInfo_C2M_BuyHero.Size(m)
}
func (m *C2M_BuyHero) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_BuyHero.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_BuyHero proto.InternalMessageInfo

func (m *C2M_BuyHero) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

// 聊天
type C2M2C_Chat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chat                 string   `protobuf:"bytes,2,opt,name=chat,proto3" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M2C_Chat) Reset()         { *m = C2M2C_Chat{} }
func (m *C2M2C_Chat) String() string { return proto.CompactTextString(m) }
func (*C2M2C_Chat) ProtoMessage()    {}
func (*C2M2C_Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{27}
}
func (m *C2M2C_Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M2C_Chat.Unmarshal(m, b)
}
func (m *C2M2C_Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M2C_Chat.Marshal(b, m, deterministic)
}
func (dst *C2M2C_Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M2C_Chat.Merge(dst, src)
}
func (m *C2M2C_Chat) XXX_Size() int {
	return xxx_messageInfo_C2M2C_Chat.Size(m)
}
func (m *C2M2C_Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M2C_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_C2M2C_Chat proto.InternalMessageInfo

func (m *C2M2C_Chat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *C2M2C_Chat) GetChat() string {
	if m != nil {
		return m.Chat
	}
	return ""
}

// 学习技能
type C2M_LearnSkill struct {
	SkillId              int32    `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	SkillPoint           int32    `protobuf:"varint,2,opt,name=skillPoint,proto3" json:"skillPoint,omitempty"`
	HeroId               int32    `protobuf:"varint,3,opt,name=heroId,proto3" json:"heroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M_LearnSkill) Reset()         { *m = C2M_LearnSkill{} }
func (m *C2M_LearnSkill) String() string { return proto.CompactTextString(m) }
func (*C2M_LearnSkill) ProtoMessage()    {}
func (*C2M_LearnSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{28}
}
func (m *C2M_LearnSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M_LearnSkill.Unmarshal(m, b)
}
func (m *C2M_LearnSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M_LearnSkill.Marshal(b, m, deterministic)
}
func (dst *C2M_LearnSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M_LearnSkill.Merge(dst, src)
}
func (m *C2M_LearnSkill) XXX_Size() int {
	return xxx_messageInfo_C2M_LearnSkill.Size(m)
}
func (m *C2M_LearnSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M_LearnSkill.DiscardUnknown(m)
}

var xxx_messageInfo_C2M_LearnSkill proto.InternalMessageInfo

func (m *C2M_LearnSkill) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *C2M_LearnSkill) GetSkillPoint() int32 {
	if m != nil {
		return m.SkillPoint
	}
	return 0
}

func (m *C2M_LearnSkill) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

// 卸载和装载技能
type C2M2C_ChangeSkill struct {
	SkillId              int32    `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	HeroId               int32    `protobuf:"varint,2,opt,name=heroId,proto3" json:"heroId,omitempty"`
	Index                int32    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M2C_ChangeSkill) Reset()         { *m = C2M2C_ChangeSkill{} }
func (m *C2M2C_ChangeSkill) String() string { return proto.CompactTextString(m) }
func (*C2M2C_ChangeSkill) ProtoMessage()    {}
func (*C2M2C_ChangeSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{29}
}
func (m *C2M2C_ChangeSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M2C_ChangeSkill.Unmarshal(m, b)
}
func (m *C2M2C_ChangeSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M2C_ChangeSkill.Marshal(b, m, deterministic)
}
func (dst *C2M2C_ChangeSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M2C_ChangeSkill.Merge(dst, src)
}
func (m *C2M2C_ChangeSkill) XXX_Size() int {
	return xxx_messageInfo_C2M2C_ChangeSkill.Size(m)
}
func (m *C2M2C_ChangeSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M2C_ChangeSkill.DiscardUnknown(m)
}

var xxx_messageInfo_C2M2C_ChangeSkill proto.InternalMessageInfo

func (m *C2M2C_ChangeSkill) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *C2M2C_ChangeSkill) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *C2M2C_ChangeSkill) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

// 获得成就
type C2M2C_GetAchievement struct {
	AchievenId           int32    `protobuf:"varint,1,opt,name=achievenId,proto3" json:"achievenId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M2C_GetAchievement) Reset()         { *m = C2M2C_GetAchievement{} }
func (m *C2M2C_GetAchievement) String() string { return proto.CompactTextString(m) }
func (*C2M2C_GetAchievement) ProtoMessage()    {}
func (*C2M2C_GetAchievement) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{30}
}
func (m *C2M2C_GetAchievement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M2C_GetAchievement.Unmarshal(m, b)
}
func (m *C2M2C_GetAchievement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M2C_GetAchievement.Marshal(b, m, deterministic)
}
func (dst *C2M2C_GetAchievement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M2C_GetAchievement.Merge(dst, src)
}
func (m *C2M2C_GetAchievement) XXX_Size() int {
	return xxx_messageInfo_C2M2C_GetAchievement.Size(m)
}
func (m *C2M2C_GetAchievement) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M2C_GetAchievement.DiscardUnknown(m)
}

var xxx_messageInfo_C2M2C_GetAchievement proto.InternalMessageInfo

func (m *C2M2C_GetAchievement) GetAchievenId() int32 {
	if m != nil {
		return m.AchievenId
	}
	return 0
}

// 获得任务奖励
type C2M2C_GetTask struct {
	TaskId               int32    `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M2C_GetTask) Reset()         { *m = C2M2C_GetTask{} }
func (m *C2M2C_GetTask) String() string { return proto.CompactTextString(m) }
func (*C2M2C_GetTask) ProtoMessage()    {}
func (*C2M2C_GetTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{31}
}
func (m *C2M2C_GetTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M2C_GetTask.Unmarshal(m, b)
}
func (m *C2M2C_GetTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M2C_GetTask.Marshal(b, m, deterministic)
}
func (dst *C2M2C_GetTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M2C_GetTask.Merge(dst, src)
}
func (m *C2M2C_GetTask) XXX_Size() int {
	return xxx_messageInfo_C2M2C_GetTask.Size(m)
}
func (m *C2M2C_GetTask) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M2C_GetTask.DiscardUnknown(m)
}

var xxx_messageInfo_C2M2C_GetTask proto.InternalMessageInfo

func (m *C2M2C_GetTask) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

// 签到奖励
type C2M2C_GetSign struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2M2C_GetSign) Reset()         { *m = C2M2C_GetSign{} }
func (m *C2M2C_GetSign) String() string { return proto.CompactTextString(m) }
func (*C2M2C_GetSign) ProtoMessage()    {}
func (*C2M2C_GetSign) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{32}
}
func (m *C2M2C_GetSign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M2C_GetSign.Unmarshal(m, b)
}
func (m *C2M2C_GetSign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M2C_GetSign.Marshal(b, m, deterministic)
}
func (dst *C2M2C_GetSign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M2C_GetSign.Merge(dst, src)
}
func (m *C2M2C_GetSign) XXX_Size() int {
	return xxx_messageInfo_C2M2C_GetSign.Size(m)
}
func (m *C2M2C_GetSign) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M2C_GetSign.DiscardUnknown(m)
}

var xxx_messageInfo_C2M2C_GetSign proto.InternalMessageInfo

// 改变自由士兵的配置
type C2M2C_ChangeFreeSoldierData struct {
	PlayerTypeIndex      int32            `protobuf:"varint,1,opt,name=playerTypeIndex,proto3" json:"playerTypeIndex,omitempty"`
	Data                 *FreeSoldierData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *C2M2C_ChangeFreeSoldierData) Reset()         { *m = C2M2C_ChangeFreeSoldierData{} }
func (m *C2M2C_ChangeFreeSoldierData) String() string { return proto.CompactTextString(m) }
func (*C2M2C_ChangeFreeSoldierData) ProtoMessage()    {}
func (*C2M2C_ChangeFreeSoldierData) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{33}
}
func (m *C2M2C_ChangeFreeSoldierData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M2C_ChangeFreeSoldierData.Unmarshal(m, b)
}
func (m *C2M2C_ChangeFreeSoldierData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M2C_ChangeFreeSoldierData.Marshal(b, m, deterministic)
}
func (dst *C2M2C_ChangeFreeSoldierData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M2C_ChangeFreeSoldierData.Merge(dst, src)
}
func (m *C2M2C_ChangeFreeSoldierData) XXX_Size() int {
	return xxx_messageInfo_C2M2C_ChangeFreeSoldierData.Size(m)
}
func (m *C2M2C_ChangeFreeSoldierData) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M2C_ChangeFreeSoldierData.DiscardUnknown(m)
}

var xxx_messageInfo_C2M2C_ChangeFreeSoldierData proto.InternalMessageInfo

func (m *C2M2C_ChangeFreeSoldierData) GetPlayerTypeIndex() int32 {
	if m != nil {
		return m.PlayerTypeIndex
	}
	return 0
}

func (m *C2M2C_ChangeFreeSoldierData) GetData() *FreeSoldierData {
	if m != nil {
		return m.Data
	}
	return nil
}

// 绑定账号
type C2M2C_BangDingZhang struct {
	ZhangHaoType         C2M2C_BangDingZhang_ZhangHaoType `protobuf:"varint,1,opt,name=zhangHaoType,proto3,enum=message.C2M2C_BangDingZhang_ZhangHaoType" json:"zhangHaoType,omitempty"`
	ZhangHao             string                           `protobuf:"bytes,2,opt,name=zhangHao,proto3" json:"zhangHao,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *C2M2C_BangDingZhang) Reset()         { *m = C2M2C_BangDingZhang{} }
func (m *C2M2C_BangDingZhang) String() string { return proto.CompactTextString(m) }
func (*C2M2C_BangDingZhang) ProtoMessage()    {}
func (*C2M2C_BangDingZhang) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2M_f523c958d9c1a9c6, []int{34}
}
func (m *C2M2C_BangDingZhang) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2M2C_BangDingZhang.Unmarshal(m, b)
}
func (m *C2M2C_BangDingZhang) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2M2C_BangDingZhang.Marshal(b, m, deterministic)
}
func (dst *C2M2C_BangDingZhang) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2M2C_BangDingZhang.Merge(dst, src)
}
func (m *C2M2C_BangDingZhang) XXX_Size() int {
	return xxx_messageInfo_C2M2C_BangDingZhang.Size(m)
}
func (m *C2M2C_BangDingZhang) XXX_DiscardUnknown() {
	xxx_messageInfo_C2M2C_BangDingZhang.DiscardUnknown(m)
}

var xxx_messageInfo_C2M2C_BangDingZhang proto.InternalMessageInfo

func (m *C2M2C_BangDingZhang) GetZhangHaoType() C2M2C_BangDingZhang_ZhangHaoType {
	if m != nil {
		return m.ZhangHaoType
	}
	return C2M2C_BangDingZhang_QQ
}

func (m *C2M2C_BangDingZhang) GetZhangHao() string {
	if m != nil {
		return m.ZhangHao
	}
	return ""
}

func init() {
	proto.RegisterType((*Room)(nil), "message.Room")
	proto.RegisterType((*LocalRole)(nil), "message.LocalRole")
	proto.RegisterType((*FreeSoldierData)(nil), "message.FreeSoldierData")
	proto.RegisterType((*RoomMember)(nil), "message.RoomMember")
	proto.RegisterType((*RoomOwner)(nil), "message.RoomOwner")
	proto.RegisterType((*Command)(nil), "message.Command")
	proto.RegisterType((*C2M_CreateRoom)(nil), "message.C2M_CreateRoom")
	proto.RegisterType((*C2M_ReqRefreshRoomList)(nil), "message.C2M_ReqRefreshRoomList")
	proto.RegisterType((*C2M_ReqJoinRoom)(nil), "message.C2M_ReqJoinRoom")
	proto.RegisterType((*C2M_ReqLocalJoinRoom)(nil), "message.C2M_ReqLocalJoinRoom")
	proto.RegisterType((*C2M_StartBattle)(nil), "message.C2M_StartBattle")
	proto.RegisterType((*C2M_ReqReady)(nil), "message.C2M_ReqReady")
	proto.RegisterType((*C2M_ReqLocalReady)(nil), "message.C2M_ReqLocalReady")
	proto.RegisterType((*C2M_LoadFinished)(nil), "message.C2M_LoadFinished")
	proto.RegisterType((*C2M_LocalLoadFinished)(nil), "message.C2M_LocalLoadFinished")
	proto.RegisterType((*C2M_Command)(nil), "message.C2M_Command")
	proto.RegisterType((*C2M_WinBattle)(nil), "message.C2M_WinBattle")
	proto.RegisterType((*C2M_FailedBattle)(nil), "message.C2M_FailedBattle")
	proto.RegisterType((*C2M_WatchAds)(nil), "message.C2M_WatchAds")
	proto.RegisterType((*C2M_ChangeNickName)(nil), "message.C2M_ChangeNickName")
	proto.RegisterType((*C2M_ChangeAvatarIcon)(nil), "message.C2M_ChangeAvatarIcon")
	proto.RegisterType((*C2M_ChangeSex)(nil), "message.C2M_ChangeSex")
	proto.RegisterType((*C2M_ChangeSign)(nil), "message.C2M_ChangeSign")
	proto.RegisterType((*C2M2C_ChangeEquipItemPos)(nil), "message.C2M2C_ChangeEquipItemPos")
	proto.RegisterType((*C2M_QuitRoom)(nil), "message.C2M_QuitRoom")
	proto.RegisterType((*C2M_LocalQuitRoom)(nil), "message.C2M_LocalQuitRoom")
	proto.RegisterType((*C2M_BuyHero)(nil), "message.C2M_BuyHero")
	proto.RegisterType((*C2M2C_Chat)(nil), "message.C2M2C_Chat")
	proto.RegisterType((*C2M_LearnSkill)(nil), "message.C2M_LearnSkill")
	proto.RegisterType((*C2M2C_ChangeSkill)(nil), "message.C2M2C_ChangeSkill")
	proto.RegisterType((*C2M2C_GetAchievement)(nil), "message.C2M2C_GetAchievement")
	proto.RegisterType((*C2M2C_GetTask)(nil), "message.C2M2C_GetTask")
	proto.RegisterType((*C2M2C_GetSign)(nil), "message.C2M2C_GetSign")
	proto.RegisterType((*C2M2C_ChangeFreeSoldierData)(nil), "message.C2M2C_ChangeFreeSoldierData")
	proto.RegisterType((*C2M2C_BangDingZhang)(nil), "message.C2M2C_BangDingZhang")
	proto.RegisterEnum("message.C2M2C_ChangeEquipItemPos_HeroToBagType", C2M2C_ChangeEquipItemPos_HeroToBagType_name, C2M2C_ChangeEquipItemPos_HeroToBagType_value)
	proto.RegisterEnum("message.C2M2C_BangDingZhang_ZhangHaoType", C2M2C_BangDingZhang_ZhangHaoType_name, C2M2C_BangDingZhang_ZhangHaoType_value)
}

func init() { proto.RegisterFile("C2M.proto", fileDescriptor_C2M_f523c958d9c1a9c6) }

var fileDescriptor_C2M_f523c958d9c1a9c6 = []byte{
	// 1294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x5d, 0x6f, 0x1c, 0x35,
	0x17, 0xee, 0xec, 0x47, 0x76, 0xf7, 0x64, 0x93, 0x6c, 0xdd, 0xbe, 0xd5, 0xe8, 0x45, 0x42, 0xc1,
	0x2a, 0x25, 0x85, 0x92, 0xb6, 0x0b, 0x42, 0xbd, 0x02, 0x25, 0xdb, 0xa6, 0x5d, 0x48, 0xda, 0x74,
	0x52, 0x11, 0x54, 0x84, 0x22, 0x67, 0xc7, 0xdd, 0x35, 0x99, 0x19, 0x6f, 0x3d, 0xb3, 0x4d, 0xc2,
	0x35, 0x3f, 0x81, 0x7b, 0x7e, 0x06, 0x12, 0xfc, 0x39, 0x74, 0x6c, 0x8f, 0xd7, 0x93, 0x2a, 0xa4,
	0x7b, 0xe7, 0xe7, 0x7c, 0xf9, 0xf8, 0x9c, 0xc7, 0x67, 0x3c, 0xd0, 0x19, 0xf4, 0xf7, 0x36, 0xa7,
	0x4a, 0x16, 0x92, 0xb4, 0x52, 0x9e, 0xe7, 0x6c, 0xcc, 0xe9, 0x11, 0x34, 0x22, 0x29, 0x53, 0xb2,
	0x01, 0x4d, 0x79, 0x9a, 0x71, 0x15, 0x06, 0xeb, 0xc1, 0xc6, 0x72, 0x9f, 0x6c, 0x5a, 0x83, 0x4d,
	0xd4, 0xbe, 0x40, 0x4d, 0x64, 0x0c, 0xc8, 0x97, 0xd0, 0x4a, 0x79, 0x7a, 0xcc, 0x55, 0x1e, 0xd6,
	0xd6, 0xeb, 0x1b, 0xcb, 0xfd, 0x1b, 0x15, 0xdb, 0x3d, 0xad, 0x8b, 0x4a, 0x1b, 0xfa, 0x57, 0x0d,
	0x3a, 0xbb, 0x72, 0xc4, 0x92, 0x48, 0x26, 0x9c, 0xdc, 0x82, 0x25, 0x25, 0x13, 0x3e, 0x8c, 0xf5,
	0x3e, 0xf5, 0xc8, 0x22, 0xf2, 0x7f, 0x68, 0x67, 0x62, 0x74, 0xf2, 0x9c, 0xa5, 0x3c, 0xac, 0xad,
	0x07, 0x1b, 0x9d, 0xc8, 0x61, 0xd4, 0xb1, 0x77, 0xac, 0x60, 0x6a, 0x18, 0x87, 0xf5, 0xf5, 0x60,
	0xa3, 0x19, 0x39, 0x4c, 0x6e, 0x42, 0x33, 0xe1, 0xef, 0x78, 0x12, 0x36, 0xb4, 0xc2, 0x00, 0xd2,
	0x87, 0x16, 0x53, 0x4a, 0x9e, 0x72, 0x15, 0x36, 0xf5, 0x71, 0x42, 0x97, 0xe2, 0x8e, 0xe2, 0xfc,
	0x40, 0x26, 0xb1, 0xe0, 0xea, 0x31, 0x2b, 0x58, 0x54, 0x1a, 0x92, 0x07, 0xb0, 0x14, 0x33, 0x19,
	0xcf, 0xb2, 0x70, 0xe9, 0x0a, 0x17, 0x6b, 0x47, 0x36, 0xa1, 0x99, 0x4f, 0x39, 0x53, 0x61, 0xeb,
	0x0a, 0x07, 0x63, 0x86, 0xf6, 0x6f, 0x58, 0x3e, 0x11, 0x61, 0xfb, 0x2a, 0x7b, 0x6d, 0x46, 0xff,
	0x0c, 0x60, 0xed, 0x82, 0x8a, 0x7c, 0x0c, 0x30, 0x4d, 0xd8, 0x39, 0x57, 0xaf, 0xce, 0xa7, 0x5c,
	0xd7, 0xb0, 0x19, 0x79, 0x12, 0xb2, 0x0e, 0xcb, 0x23, 0xa6, 0x94, 0xb0, 0x06, 0x35, 0x6d, 0xe0,
	0x8b, 0xb0, 0x9a, 0x85, 0x9c, 0xfd, 0x30, 0x13, 0xf3, 0x6a, 0x96, 0x18, 0xbb, 0x73, 0x2c, 0xe3,
	0xf3, 0x61, 0x6c, 0xcb, 0x69, 0x11, 0xca, 0x4f, 0x39, 0x9b, 0x0e, 0x63, 0x5d, 0xce, 0x66, 0x64,
	0x11, 0xfd, 0xbd, 0x0e, 0x30, 0xef, 0x39, 0x86, 0xfe, 0x55, 0x8a, 0x8c, 0x2b, 0xd7, 0x5e, 0x87,
	0x31, 0x71, 0xb3, 0xf6, 0x5a, 0xec, 0x49, 0x08, 0x85, 0xae, 0xb5, 0x1d, 0xc9, 0xcc, 0xa5, 0x56,
	0x91, 0x91, 0x10, 0x5a, 0x63, 0x25, 0x67, 0x53, 0x97, 0x5f, 0x09, 0xf1, 0xd8, 0xc6, 0x72, 0x57,
	0x93, 0xc1, 0x64, 0xe9, 0x8b, 0x90, 0x28, 0x8a, 0xb3, 0xf8, 0x5c, 0x77, 0xb7, 0x1d, 0x19, 0xe0,
	0x13, 0xa5, 0xb5, 0x38, 0x51, 0xda, 0x8b, 0x12, 0xa5, 0xb3, 0x20, 0x51, 0xe0, 0xc3, 0x88, 0xf2,
	0x4f, 0x03, 0x3a, 0xee, 0x9a, 0x62, 0x17, 0xc6, 0x2c, 0xe5, 0x1e, 0x41, 0x1c, 0x46, 0x9d, 0x92,
	0x32, 0xf5, 0xaf, 0x59, 0x89, 0xb1, 0x03, 0x29, 0x3b, 0xdb, 0xd7, 0x5c, 0x7a, 0x3e, 0x4b, 0xcb,
	0x0e, 0xf8, 0x32, 0xac, 0x62, 0xca, 0xe6, 0xf5, 0x37, 0x80, 0xdc, 0x86, 0x15, 0x55, 0x6e, 0xaf,
	0x43, 0x37, 0x75, 0xe8, 0xaa, 0x10, 0x7b, 0xe4, 0x04, 0xc3, 0x58, 0xf7, 0xa1, 0x1e, 0xf9, 0x22,
	0x33, 0x1c, 0x64, 0x3a, 0x8c, 0x75, 0x33, 0x9a, 0x91, 0x45, 0x9a, 0xd4, 0x33, 0xa5, 0xb3, 0xc0,
	0xc4, 0xda, 0x96, 0xd4, 0x73, 0x11, 0xf9, 0x1c, 0x7a, 0x2e, 0xd0, 0x53, 0x4b, 0x91, 0x8e, 0x36,
	0x7b, 0x4f, 0x8e, 0x35, 0x10, 0xf9, 0x21, 0x53, 0x3b, 0xf2, 0x54, 0x17, 0xb8, 0x1d, 0x39, 0x4c,
	0xee, 0xc1, 0x75, 0x67, 0xbf, 0x55, 0xce, 0x9c, 0x65, 0x1d, 0xe8, 0x7d, 0x85, 0xcf, 0x9e, 0xee,
	0xe2, 0xec, 0x59, 0x59, 0x94, 0x3d, 0xab, 0x0b, 0xb2, 0x67, 0xed, 0xc3, 0xd8, 0xf3, 0x0b, 0xb4,
	0x06, 0x32, 0x4d, 0x59, 0xa6, 0x4b, 0x63, 0x66, 0x89, 0xbd, 0xc0, 0xcd, 0xc8, 0x61, 0xdd, 0x04,
	0x63, 0x56, 0x99, 0x2c, 0x73, 0x11, 0x92, 0x63, 0xca, 0x14, 0x33, 0xcc, 0xe9, 0x44, 0x06, 0xd0,
	0x47, 0xb0, 0x3a, 0xe8, 0xef, 0x1d, 0x0d, 0x14, 0x67, 0x05, 0xd7, 0x9f, 0x9a, 0x3b, 0xd0, 0xc0,
	0x5a, 0xfe, 0xc7, 0x97, 0x46, 0xeb, 0x69, 0x08, 0xb7, 0xd0, 0x33, 0xe2, 0x6f, 0x23, 0xfe, 0x46,
	0xf1, 0x7c, 0x82, 0x06, 0xbb, 0x22, 0x2f, 0xe8, 0x5d, 0x58, 0xb3, 0x9a, 0xef, 0xa5, 0xc8, 0x74,
	0xd0, 0x39, 0x77, 0x02, 0x9f, 0x3b, 0xf4, 0x47, 0xb8, 0x69, 0x4d, 0xf5, 0x47, 0xe8, 0x2a, 0x7b,
	0x93, 0x5c, 0x62, 0xce, 0xe7, 0x27, 0xe7, 0x3e, 0x61, 0x91, 0xd6, 0xd3, 0xeb, 0x26, 0x85, 0x83,
	0x82, 0xa9, 0x62, 0x9b, 0x15, 0x45, 0xc2, 0xe9, 0x6d, 0xe8, 0xba, 0x7c, 0x71, 0xb8, 0xb8, 0x91,
	0x13, 0x78, 0x23, 0x87, 0x6e, 0xc1, 0x75, 0x3f, 0x21, 0x63, 0x7a, 0xd9, 0x67, 0xd1, 0x85, 0xa8,
	0xf9, 0x21, 0x08, 0xf4, 0x30, 0xc4, 0xae, 0x64, 0xf1, 0x8e, 0xc8, 0x44, 0x3e, 0xe1, 0x31, 0xbd,
	0x0f, 0xff, 0x33, 0xb2, 0x11, 0x4b, 0x7c, 0xc5, 0x65, 0xa1, 0xe9, 0x43, 0x58, 0xd6, 0x7d, 0xb1,
	0xad, 0xa7, 0x50, 0x1f, 0xa5, 0xb1, 0xed, 0x49, 0xcf, 0x1d, 0xdb, 0xaa, 0x23, 0x54, 0xd2, 0xef,
	0x60, 0x05, 0x5d, 0x0e, 0x45, 0x66, 0x4e, 0x4c, 0x08, 0x34, 0x72, 0xce, 0xcb, 0x12, 0xea, 0x35,
	0x72, 0xe8, 0x58, 0x6b, 0x87, 0xb1, 0x25, 0x89, 0xc3, 0xf4, 0x8e, 0x49, 0x7c, 0x87, 0x89, 0x84,
	0xc7, 0x97, 0xc7, 0xa0, 0xdf, 0x9a, 0x4a, 0x1e, 0xb2, 0x62, 0x34, 0xd9, 0x8a, 0x73, 0x73, 0x65,
	0xb7, 0x59, 0x56, 0xbe, 0x4f, 0xf4, 0x95, 0x35, 0xd8, 0xf9, 0xd7, 0x3c, 0xff, 0x07, 0x40, 0xf4,
	0xd9, 0x26, 0x2c, 0x1b, 0xf3, 0xe7, 0xde, 0x3b, 0xc2, 0xbd, 0x31, 0x82, 0xea, 0x1b, 0x83, 0xf6,
	0x0d, 0x4d, 0x8c, 0x87, 0xbd, 0xe0, 0x23, 0x99, 0x55, 0xde, 0x1e, 0x41, 0xf5, 0xed, 0x41, 0x3f,
	0x31, 0xe5, 0x30, 0x3e, 0x07, 0xfc, 0x8c, 0xf4, 0xa0, 0x9e, 0xf3, 0x33, 0x6b, 0x87, 0x4b, 0x7a,
	0xdb, 0x92, 0xdf, 0x98, 0x88, 0x71, 0xa6, 0xd3, 0x15, 0xe3, 0xcc, 0x26, 0xa0, 0xd7, 0xf4, 0x8f,
	0x1a, 0x84, 0x83, 0xfe, 0x5e, 0x7f, 0x60, 0x0d, 0x9f, 0xbc, 0x9d, 0x89, 0xe9, 0xb0, 0xe0, 0xe9,
	0xbe, 0xcc, 0xc9, 0x0b, 0x80, 0x91, 0x96, 0xba, 0x81, 0xbe, 0xda, 0xbf, 0x3f, 0xef, 0xcf, 0x25,
	0x6e, 0x9b, 0xcf, 0xb8, 0x92, 0xaf, 0xe4, 0x36, 0x1b, 0xa3, 0x5b, 0xe4, 0x85, 0x40, 0x42, 0x88,
	0x2c, 0xe6, 0x67, 0x0f, 0x6d, 0xc9, 0x2c, 0x72, 0xf2, 0xbe, 0x9d, 0xfc, 0x16, 0xa1, 0x7c, 0xc2,
	0x95, 0x9c, 0x3f, 0x0a, 0x0c, 0xa2, 0x47, 0xb0, 0x52, 0xd9, 0x84, 0xac, 0x40, 0xc7, 0x09, 0x7a,
	0xd7, 0x10, 0xa2, 0x46, 0xa2, 0xac, 0x17, 0x90, 0x2e, 0xb4, 0x35, 0x44, 0x65, 0x8d, 0xf4, 0xa0,
	0x6b, 0x47, 0x91, 0x91, 0xd4, 0x51, 0xa2, 0xf5, 0x56, 0xdc, 0x6b, 0xd0, 0x55, 0xc3, 0x82, 0x97,
	0x33, 0x51, 0xe0, 0x95, 0xa5, 0x5f, 0x98, 0x9b, 0xa3, 0x29, 0x5e, 0x0a, 0x2f, 0xa5, 0xf7, 0xa7,
	0x86, 0xde, 0xdb, 0xb3, 0x73, 0xdc, 0xdf, 0x3b, 0x44, 0x50, 0x39, 0xc4, 0xd7, 0x00, 0xae, 0x84,
	0x05, 0x36, 0x27, 0x9b, 0xb3, 0x43, 0xaf, 0x51, 0x36, 0x9a, 0xb0, 0xc2, 0x7e, 0x2e, 0xf5, 0x9a,
	0x1e, 0x9b, 0xb6, 0xee, 0x72, 0xa6, 0xb2, 0x83, 0x13, 0x91, 0x24, 0xf8, 0x34, 0xc9, 0x71, 0xe1,
	0x36, 0x28, 0x21, 0x3e, 0x7c, 0xf4, 0x72, 0x5f, 0x8a, 0xac, 0xb0, 0x25, 0xf7, 0x24, 0x5e, 0x66,
	0xf5, 0x4a, 0x66, 0x3f, 0xeb, 0xd3, 0xba, 0xe6, 0x5e, 0xb5, 0xcd, 0x3c, 0x4c, 0xcd, 0x0f, 0x83,
	0x13, 0x44, 0xf7, 0xd1, 0x46, 0x37, 0x80, 0x7e, 0xa3, 0xe9, 0xde, 0x1f, 0x1c, 0x3d, 0xe5, 0xc5,
	0xd6, 0x68, 0x22, 0xf8, 0x3b, 0x9e, 0xf2, 0xac, 0xc0, 0x64, 0x99, 0x81, 0x99, 0xdb, 0xc2, 0x93,
	0xd0, 0xcf, 0x34, 0xe5, 0x8d, 0xdf, 0x2b, 0x96, 0x9f, 0xe0, 0xb6, 0x05, 0xcb, 0x4f, 0xe6, 0x75,
	0x35, 0x88, 0xae, 0x79, 0x86, 0xc8, 0x7b, 0x3a, 0x83, 0x8f, 0xfc, 0xe3, 0x5c, 0x7c, 0xd7, 0x6e,
	0xc0, 0xda, 0xfc, 0x15, 0x3b, 0xd4, 0x09, 0x9b, 0x80, 0x17, 0xc5, 0xe4, 0x1e, 0x34, 0x62, 0x56,
	0x30, 0x3b, 0xa0, 0x2f, 0xff, 0xba, 0x69, 0x2b, 0xfa, 0x77, 0x00, 0x37, 0xcc, 0xbe, 0xdb, 0x2c,
	0x1b, 0x3f, 0x16, 0xd9, 0xf8, 0x35, 0xee, 0x4f, 0xf6, 0xa0, 0xfb, 0x1b, 0x2e, 0x9e, 0x31, 0xe9,
	0xdd, 0xab, 0xbb, 0x17, 0xee, 0x55, 0xc5, 0x67, 0xf3, 0xb5, 0xe7, 0x10, 0x55, 0xdc, 0x71, 0x4c,
	0x94, 0xb8, 0x7c, 0x57, 0x95, 0x98, 0x3e, 0x82, 0xae, 0xef, 0x49, 0x96, 0xa0, 0xf6, 0xf2, 0x65,
	0xef, 0x1a, 0x01, 0x58, 0x3a, 0xe4, 0xe2, 0x27, 0x91, 0xf5, 0x02, 0xd2, 0x81, 0xe6, 0x93, 0x94,
	0x89, 0xa4, 0x57, 0xc3, 0xe5, 0xfe, 0x44, 0x66, 0xbc, 0x57, 0x3f, 0x5e, 0xd2, 0xff, 0x6a, 0x5f,
	0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x87, 0xa2, 0x19, 0xda, 0xb8, 0x0d, 0x00, 0x00,
}
